apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hacka-api
  labels:
    app: hacka-api
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hacka-api-service
                port:
                  number: 9000
