apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacka-api
  labels:
    app: hacka-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacka-api
  template:
    metadata:
      labels:
        app: hacka-api
    spec:
      containers:
        - name: hacka-api
          image: wolwer/hacka-app:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_ROOT_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MYSQL_PASSWORD
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MYSQL_ALLOW_EMPTY_PASSWORD
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /up
              port: 9000
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /up
              port: 9000
            initialDelaySeconds: 180
            periodSeconds: 30
