apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-hacka-pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-hacka-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/mysql-hacka"